// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0

package database

import (
	"database/sql"
	"time"

	"github.com/google/uuid"
)

type Chat struct {
	ChatID    int32
	StudentID uuid.UUID
	TutorID   uuid.NullUUID
	CreatedAt time.Time
	SubjectID int32
	Topic     sql.NullString
	Header    string
	PhotoUrl  sql.NullString
	Completed bool
}

type ChatTopic struct {
	ChatID  int32
	TopicID int32
}

type Message struct {
	MessageID uuid.UUID
	ChatID    int32
	UserID    uuid.UUID
	CreatedAt time.Time
	UpdatedAt time.Time
	Deleted   bool
	Content   string
}

type Student struct {
	StudentID      uuid.UUID
	Username       string
	Email          string
	CreatedAt      time.Time
	Name           string
	Valid          bool
	HashedPassword string
}

type Subject struct {
	SubjectID int32
	Name      string
}

type Topic struct {
	SubjectID int32
	TopicID   int32
	Name      sql.NullString
}

type Tutor struct {
	TutorID        uuid.UUID
	Username       string
	Email          string
	CreatedAt      time.Time
	Name           string
	Valid          bool
	HashedPassword string
	Verified       bool
	Rating         sql.NullFloat64
	RatingCount    int32
}

type TutorSubject struct {
	TutorID   uuid.UUID
	SubjectID int32
	Yoe       int32
}

type User struct {
	UserID   uuid.UUID
	Username string
	Email    string
	UserType string
}
