// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0

package database

import (
	"database/sql"
	"time"

	"github.com/google/uuid"
)

type Chat struct {
	ChatID    int32
	StudentID uuid.UUID
	TutorID   uuid.NullUUID
	CreatedAt time.Time
	Subject   string
	Topic     sql.NullString
	Header    string
	Completed bool
}

type Message struct {
	MessageID uuid.UUID
	ChatID    int32
	UserID    uuid.UUID
	CreatedAt time.Time
	UpdatedAt time.Time
	Deleted   bool
	Content   string
}

type Student struct {
	StudentID      uuid.UUID
	Username       string
	Email          string
	CreatedAt      time.Time
	Name           string
	Valid          bool
	HashedPassword string
}

type Tutor struct {
	TutorID        uuid.UUID
	Username       string
	Email          string
	CreatedAt      time.Time
	Name           string
	Valid          bool
	HashedPassword string
	Yoe            int32
	Subject        string
	Verified       bool
	Rating         sql.NullFloat64
	RatingCount    int32
}

type User struct {
	UserID   uuid.UUID
	Username string
	UserType string
}
