// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0
// source: students.sql

package database

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createNewStudent = `-- name: CreateNewStudent :one
INSERT INTO students (student_id, username, email, created_at, name, valid, hashed_password)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING student_id, username, email, created_at, name, valid, hashed_password
`

type CreateNewStudentParams struct {
	StudentID      uuid.UUID
	Username       string
	Email          string
	CreatedAt      time.Time
	Name           string
	Valid          bool
	HashedPassword string
}

func (q *Queries) CreateNewStudent(ctx context.Context, arg CreateNewStudentParams) (Student, error) {
	row := q.db.QueryRowContext(ctx, createNewStudent,
		arg.StudentID,
		arg.Username,
		arg.Email,
		arg.CreatedAt,
		arg.Name,
		arg.Valid,
		arg.HashedPassword,
	)
	var i Student
	err := row.Scan(
		&i.StudentID,
		&i.Username,
		&i.Email,
		&i.CreatedAt,
		&i.Name,
		&i.Valid,
		&i.HashedPassword,
	)
	return i, err
}

const getStudentById = `-- name: GetStudentById :one
SELECT student_id, username, email, created_at, name, valid, hashed_password FROM students WHERE student_id = $1
`

func (q *Queries) GetStudentById(ctx context.Context, studentID uuid.UUID) (Student, error) {
	row := q.db.QueryRowContext(ctx, getStudentById, studentID)
	var i Student
	err := row.Scan(
		&i.StudentID,
		&i.Username,
		&i.Email,
		&i.CreatedAt,
		&i.Name,
		&i.Valid,
		&i.HashedPassword,
	)
	return i, err
}

const getStudentByUsername = `-- name: GetStudentByUsername :one
SELECT student_id, username, email, created_at, name, valid, hashed_password FROM students WHERE username = $1
`

func (q *Queries) GetStudentByUsername(ctx context.Context, username string) (Student, error) {
	row := q.db.QueryRowContext(ctx, getStudentByUsername, username)
	var i Student
	err := row.Scan(
		&i.StudentID,
		&i.Username,
		&i.Email,
		&i.CreatedAt,
		&i.Name,
		&i.Valid,
		&i.HashedPassword,
	)
	return i, err
}

const getStudentHash = `-- name: GetStudentHash :one
SELECT hashed_password FROM students WHERE username = $1
`

func (q *Queries) GetStudentHash(ctx context.Context, username string) (string, error) {
	row := q.db.QueryRowContext(ctx, getStudentHash, username)
	var hashed_password string
	err := row.Scan(&hashed_password)
	return hashed_password, err
}

const updateStudentPassword = `-- name: UpdateStudentPassword :exec
UPDATE students SET hashed_password = $1 WHERE student_id = $2
`

type UpdateStudentPasswordParams struct {
	HashedPassword string
	StudentID      uuid.UUID
}

func (q *Queries) UpdateStudentPassword(ctx context.Context, arg UpdateStudentPasswordParams) error {
	_, err := q.db.ExecContext(ctx, updateStudentPassword, arg.HashedPassword, arg.StudentID)
	return err
}

const updateStudentProfile = `-- name: UpdateStudentProfile :one
UPDATE students SET username = $1, name = $2, email = $3 WHERE student_id = $4
RETURNING student_id, username, email, created_at, name, valid, hashed_password
`

type UpdateStudentProfileParams struct {
	Username  string
	Name      string
	Email     string
	StudentID uuid.UUID
}

func (q *Queries) UpdateStudentProfile(ctx context.Context, arg UpdateStudentProfileParams) (Student, error) {
	row := q.db.QueryRowContext(ctx, updateStudentProfile,
		arg.Username,
		arg.Name,
		arg.Email,
		arg.StudentID,
	)
	var i Student
	err := row.Scan(
		&i.StudentID,
		&i.Username,
		&i.Email,
		&i.CreatedAt,
		&i.Name,
		&i.Valid,
		&i.HashedPassword,
	)
	return i, err
}
